language: minimal
dist: bionic
sudo: false

addons:
  apt:
    update: true
    packages:
      - p7zip
      - wine-stable
      - wine32

script:
  - ./extra/appearance.sh

env:
  global:
    - extra_dir: extra
    - bin_dir: extra/bin
    - appearance_dir: appearance
    - release_dir: release
    - WINEARCH: win32
    - WINEDEBUG: -all

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - hero_appearance*.zip
  skip_cleanup: true
  on:
    tags: true
    branch: master
