name: package

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: devopsx/gha-ubuntu-i386-fix@master

      - name: Install packages
        run: |
          sudo DEBIAN_FRONTEND=noninteractive eatmydata apt-get install -o=Dpkg::Use-Pty=0 -y p7zip
          WINEARCH=win32 eatmydata wineboot

      - name: Package
        run: ./extra/package.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          name: hero_appearance.zip
          path: hero_appearance*.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: hero_appearance*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
