name: package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: devopsx/gha-focal-i386-fix@master
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          set -xeu -o pipefail
          sudo apt-get -qq install -o=Dpkg::Use-Pty=0 -y p7zip wine-stable wine32
          wineboot

      - name: Package
        run: ./extra/package.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          name: hero_appearance.zip
          path: hero_appearance*.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: hero_appearance*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
